name: Code Linters

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Lint PHP
      uses: next-press/github-actions-linters/actions/phpcs@master
    - name: Lint JS
      uses: next-press/github-actions-linters/actions/eslint@master
